### ISSUE TITLE
Gio.PropertyAction does not work on Debian Jessie

### ISSUE THREAD

**Issue by kellerben** [gtimelog/gtimelog#100]
The followingexception is raised on my machine:
```
Traceback (most recent call last):
  File "/home/ben/src/gtimelog/src/gtimelog/main.py", line 229, in do_command_line
    self.do_activate()
  File "/home/ben/src/gtimelog/src/gtimelog/main.py", line 359, in do_activate
    window = Window(self)
  File "/home/ben/src/gtimelog/src/gtimelog/main.py", line 614, in __init__
    self.actions = self.Actions(self)
  File "/home/ben/src/gtimelog/src/gtimelog/main.py", line 498, in __init__
    self.detail_level = PropertyAction.new("detail-level", win, "detail-level")
ValueError: Pointer arguments are restricted to integers, capsules, and None. See: https://bugzilla.gnome.org/show_bug.cgi?id=683599
```
```
$ python --version
Python 2.7.9
$ python -c "import gi; print gi.__version__"
3.14.0
```
everything works if I use the FakePropertyAction (in main.py:493)
```
PropertyAction = FakePropertyAction
```

**Comment by mgedmin** [comment]
Thank you for the bug report!
