### ISSUE TITLE
Create a Flatpak package

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#106]
~~I've no idea where to start.~~

We have an experimental Flatpak package.

TODO:

- [x] figure out how to make it possible to send mail
- [x] figure out if it's possible to share the data directory with gtimelog installed from other sources
- [x] upload to Flathub.

**Comment by mgedmin** [comment]
FWIW an alternative way of sending email would be to use the [Email portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.Email).

**Comment by mgedmin** [comment]
I merged the SMTP branch and now GnomeKeyring is a mandatory dependency and flatpak'd gtimelog fails to run:

```
Traceback (most recent call last):
  File "/app/bin/gtimelog", line 11, in <module>
    load_entry_point('gtimelog==0.12.0.dev0', 'gui_scripts', 'gtimelog')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/app/lib/python3.7/site-packages/gtimelog/main.py", line 66, in <module>
    gi.require_version('GnomeKeyring', '1.0')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GnomeKeyring not available
```

**Comment by mgedmin** [comment]
It would appear that it is _possible_ to talk to gnome-keyring from a flatpak container: https://github.com/flatpak/flatpak/issues/362#issuecomment-461737946.

what fractal does is adds `-talk-name=org.freedesktop.secrets` to `finish-args` in the manifest and then... TBH I'm not sure what then.

**Comment by mgedmin** [comment]
`libsecret` is explicitly part of the GNOME runtime: http://docs.flatpak.org/en/latest/available-runtimes.html.

> libsecret is a library for storing and retrieving passwords and other secrets. It communicates with the "Secret Service" using D-Bus. gnome-keyring and ksecretservice are both implementations of a Secret Service.
>
> libsecret replaces libgnome-keyring.

It has bindings and documentation: https://lazka.github.io/pgi-docs/#Secret-1

**Comment by mgedmin** [comment]
Current status: email sending works in the Flatpak!

Now, how do I upload this thing to Flathub?

**Comment by mgedmin** [comment]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by gdesmott** [comment]
I'm trying the package and get this error when starting the app:

```
$ make flatpak-install
# you may need to install the platform and sdk before this will work
# flatpak install flathub org.gnome.Platform//3.38 org.gnome.Sdk//3.38
# note that this builds the code from git master, not your local working tree!
flatpak-builder --force-clean build/flatpak flatpak/org.gtimelog.GTimeLog.yaml --install --user
Downloading sources
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /var/home/cassidy/dev/gtimelog/.flatpak-builder/git/https_github.com_gtimelog_gtimelog.git-X54F80/
Fetching git repo https://github.com/gtimelog/gtimelog.git, ref refs/heads/master
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 84 (delta 5), reused 28 (delta 0), pack-reused 0
Receiving objects: 100% (84/84), 289.93 KiB | 4.39 MiB/s, done.
Resolving deltas: 100% (5/5), done.
From https://github.com/gtimelog/gtimelog
 * [new branch]      master     -> master
Initializing build dir
Committing stage init to cache
Starting build of org.gtimelog.GTimeLog
========================================================================
Building module gtimelog in /var/home/cassidy/dev/gtimelog/.flatpak-builder/build/gtimelog-1
========================================================================
Already on 'master'
Running: make mo-files
msgfmt -o src/gtimelog/locale/en/LC_MESSAGES/gtimelog.mo src/gtimelog/po/en.po
msgfmt -o src/gtimelog/locale/fr/LC_MESSAGES/gtimelog.mo src/gtimelog/po/fr.po
msgfmt -o src/gtimelog/locale/lt/LC_MESSAGES/gtimelog.mo src/gtimelog/po/lt.po
msgfmt -o src/gtimelog/locale/nb/LC_MESSAGES/gtimelog.mo src/gtimelog/po/nb.po
Running: pip3 install --prefix=/app --no-deps .
Processing /run/build/gtimelog
Building wheels for collected packages: gtimelog
  Building wheel for gtimelog (setup.py) ... done
  Created wheel for gtimelog: filename=gtimelog-0.12.0.dev0-py2.py3-none-any.whl size=240193 sha256=9fe472dd169e568b509849406510000f5d9a607db80c42d31d340b160f25ccb3
  Stored in directory: /tmp/pip-ephem-wheel-cache-1fwwrjew/wheels/4c/c2/ce/10f9a58497da65acdd4bb1957ef1fd7399600362f9e76b1cd5
Successfully built gtimelog
Installing collected packages: gtimelog
Successfully installed gtimelog
Running: install -D -m 644 gtimelog.desktop /app/share/applications/gtimelog.desktop
Running: install -D -m 644 src/gtimelog/gtimelog-large.png /app/share/icons/hicolor/256x256/apps/gtimelog.png
Committing stage build-gtimelog to cache
Cleaning up
Renaming gtimelog.desktop to org.gtimelog.GTimeLog.desktop
Renaming icon hicolor/256x256/apps/gtimelog.png to hicolor/256x256/apps/org.gtimelog.GTimeLog.png
Rewriting contents of org.gtimelog.GTimeLog.desktop
Committing stage cleanup to cache
Finishing app
Exporting share/applications/org.gtimelog.GTimeLog.desktop
Exporting share/icons/hicolor/256x256/apps/org.gtimelog.GTimeLog.png
Please review the exported files and the metadata
Committing stage finish to cache
Exporting org.gtimelog.GTimeLog to repo
Commit: a9d58a93441b4d851867b6cac0fd554e5fbfd9ca2ebf402f4a905599fb3a26d3
Metadata Total: 71
Metadata Written: 2
Content Total: 63
Content Written: 0
Content Bytes Written: 0 (0 bytes)
Installing app/org.gtimelog.GTimeLog/x86_64/master
Pruning cache
# to run it do
# flatpak run org.gtimelog.GTimeLog

$ flatpak run org.gtimelog.GTimeLog
bwrap: Can't find source path /run/user/1000/doc/by-app/org.gtimelog.GTimeLog: No such file or directory
```

**Comment by hfiguiere** [comment]
Here is he flathub submission

https://github.com/flathub/flathub/pull/4440

**Comment by hfiguiere** [comment]
if you want access to the repo when it's merged /  submitted, please say so.

**Comment by mgedmin** [comment]
Note to self: I should put a link to Flathub on the gtimelog website.
