### ISSUE TITLE
GSettings schema for org.gtimelog is missing

### ISSUE THREAD

**Issue by nick87720z** [gtimelog/gtimelog#172]
I under gentoo, packaged in personal overlay. Versions before 0.11 were ok. But since 0.11 (including current git head) it makes this:
`WARNING: GSettings schema for org.gtimelog is missing!  If you're running from a source checkout, be sure to run 'make'.`

I also tried right in source tree, still with same error:
```
python3 ./setup.py build
make
./gtimelog
```

**Comment by mgedmin** [comment]
The current git master should work right after a clone, with no build steps required, if you have all the necessary dependencies.  `./gtimelog` is supposed to build the schema automatically.  (`make` is still an option if you want to build stuff in advance, and not at runtime.)

Does `./gtimelog` print anything, like `Compiling GSettings schema` and `Failed: (reason why)`?

Do you have `GSETTINGS_SCHEMA_DIR` set in your environment?  That's one way to suppress the automatic build (but then `make` should build it, or at least fail).

Does `make` print anything?  What if you try from a clean checkout, with `git clean -dfx && make`?

Do you have a `glib-compile-schemas` in your `$PATH`?

Let's figure this out.

**Comment by nick87720z** [comment]
When doing make (I tried `make clean` instead of git command), I get only this:
```
$ make
rst2man.py gtimelog.rst > gtimelog.1
msgfmt -o src/gtimelog/locale/lt/LC_MESSAGES/gtimelog.mo src/gtimelog/po/lt.po
msgfmt -o src/gtimelog/locale/en/LC_MESSAGES/gtimelog.mo src/gtimelog/po/en.po
```
glib-compile-schemas presents.
GSETTINGS_SCHEMA_DIR... mm, by some reason it points to `~/data` (still have to inspect about it).

Finally, I could run it with this variable set to nothing:
(despite traceback, gui appears and app doesn't crash)
```
$ GSETTINGS_SCHEMA_DIR= ./gtimelog
Traceback (most recent call last):
  File "/home/nick87720z/dist/gtimelog/src/gtimelog/main.py", line 997, in gained_focus
    self.check_reload()
  File "/home/nick87720z/dist/gtimelog/src/gtimelog/main.py", line 1345, in check_reload
    if self.timelog.check_reload():
AttributeError: 'NoneType' object has no attribute 'check_reload'
```

**Comment by nick87720z** [comment]
On my system all (most) schemas are at `/usr/share/glib-2.0/schemas`.
While for gtimelog all resources (including ui and png) are in python package.

**Comment by mgedmin** [comment]
The idea is that a distro packager will build a package that installs the schema into /usr/share/blahblah, but I also tried to make things work out of the box for people running from source.  Making things work requires two things:
- ~~magical schema compilations~~ (originally I wasn't sure the precompiled binary schema is sufficiently architecture independent that I could just git commit it, but I eventually learned it was actually arch-independent and I did git commit it!  this is why `make` didn't build it!)
- setting GSETTINGS_SCHEMA_DIR so it can be found

Why do you have GSETTINGS_SCHEMA_DIR set in your environment?  Is this a distribution default, or something you've customized for your own reasons?

I've opted not to override it if it's already set in fear of breaking something else (like GTK itself), since I don't think it supports multiple directories separated by a colon?  But maybe it does?  Augh software is hard.

(This is why I want to get the Flatpak done, which is also hard.  But hopefully it would be hard _once_.)

**Comment by mathause** [comment]
I wanted to install gtimelog into a conda environment which has glib installed. glib (as installed by conda) sets the `GSETTINGS_SCHEMA_DIR` here:

https://github.com/conda-forge/glib-feedstock/blob/f72ebb3763fc52b928a2d15bb26a6db8a4d7b166/recipe/scripts/activate.sh#L2

So what I did is copy the gtimelog schema over and compile them:

```bash
conda activate environment
cp $CONDA_PREFIX/lib/python3.9/site-packages/gtimelog/data/org.gtimelog.gschema.xml $CONDA_PREFIX/share/glib-2.0/schemas/
glib-compile-schemas $CONDA_PREFIX/share/glib-2.0/schemas/
```

(What I don't entirely understand - on my personal computer it works just fine and `GSETTINGS_SCHEMA_DIR` is not set while for my work computer I need this hack...)
