### ISSUE TITLE
DistributionNotFound

### ISSUE THREAD

**Issue by bachy** [gtimelog/gtimelog#203]
Hi,
on archlinux fully updated, today gtimelog refuse to launch
```
$ gtimelog 
Traceback (most recent call last):
  File "/usr/bin/gtimelog", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gtimelog==0.11.3' distribution was not found and is required by the application
```
is it from arch or gtimelog ?
installed with https://aur.archlinux.org/packages/gtimelog/

**Comment by mgedmin** [comment]
This sounds like an Arch problem.  I looked at https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gtimelog, and I see nothing obviously wrong there, but I don't use Arch myself and I don't think I'm qualified to solve this.

Usually this kind of problem means that you installed a Python package into a different version of the Python interpreter than the one you're now trying to run with.  E.g. if at some point /usr/bin/python3 was python3.8, and you install gtimelog in a way that creates a /usr/bin/gtimelog wrapper script with a `#!/usr/bin/python3` shebang line, and then you upgrade your python so /usr/bin/python3 is now python3.9, that's the error you would get.

If that's the case, the fix would be to reinstall gtimelog from AUR.

**Comment by bachy** [comment]
yes it worked with a reinstall, thank you !!
