### ISSUE TITLE
gi.RepositoryError: Typelib file for namespace 'GObject', version '2.0' not found

### ISSUE THREAD

**Issue by samtuke** [gtimelog/gtimelog#252]
I'm getting this error on Mac M2 hardware today. I've been running gtimelog from git for months, not sure what's causing it. libx11 was upgraded also today, in case that's related by any chance. Ideas?

```
~/D/gtimelog (master)> gtimelog
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/gi/importer.py", line 139, in create_module
    introspection_module = get_introspection_module(namespace)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gi/module.py", line 263, in get_introspection_module
    module = IntrospectionModule(namespace, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gi/module.py", line 110, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'GObject', version '2.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/gtimelog", line 5, in <module>
    from gtimelog.main import main
  File "/opt/homebrew/lib/python3.11/site-packages/gtimelog/main.py", line 72, in <module>
    from gi.repository import Gdk, Gio, GLib, GObject, Gtk, Pango, Soup
  File "/opt/homebrew/lib/python3.11/site-packages/gi/importer.py", line 141, in create_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'GObject', version '2.0' not found
```

**Comment by sallner** [comment]
Hello, 
I got the same error. It is actually the version `1.80` of `gobject-introspection`, which does not well with `gtimelog`.

My workaround was to downgrade to `1.78.1`. If you use `homebrew`, those steps might help, as long no other dependency needs the new `gobject-introspection` version. I pinned the version in the last step to avoid another automatic upgrade.

```
brew info gobject-introspection
# Uninstall the old version. Alternatively `unlink` could also work.
brew uninstall gobject-introspection
curl -o gobject-introspection.rb  https://raw.githubusercontent.com/Homebrew/homebrew-core/abdcdb4613d762c58b0d59ae97f34e92e00f493d/Formula/g/gobject-introspection.rb
brew install -s gobject-introspection.rb
brew pin gobject-introspection
```

**Comment by samtuke** [comment]
@sallner That worked! Awesome; thanks for taking the time to share 🙏

**Comment by samtuke** [comment]
Not sure whether to close this (due to the workaround) or not... I'll change the issue name to make it more relevant for the future, and keep it open (maintainers: feel free to close instead, of course).

**Comment by mgedmin** [comment]
> gi.RepositoryError: Typelib file for namespace 'GObject', version '2.0' not found

I'm not familiar with Homebrew, but this error means the **GObject-2.0.typelib** file is not installed.  On Ubuntu it's provided by the **gir1.2-glib-2.0** package and resides in /usr/lib/x86_64-linux-gnu/girepository-1.0/

**Comment by tjwilli58** [comment]
> Not sure whether to close this (due to the workaround) or not... I'll change the issue name to make it more relevant for the future, and keep it open (maintainers: feel free to close instead, of course).

I'm also getting this trying to build gstreamer. I finally got it built, but when I try to `from gi.repository import Gst` I get the same error.
```
Python 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.version_info
(3, 50, 1)
>>> gi.require_version('Gst','1.0')
>>> from gi.repository import Gst
Traceback (most recent call last):
  File "D:\opt\gstreamer\lib\site-packages\gi\importer.py", line 139, in create_module
    introspection_module = get_introspection_module(namespace)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\opt\gstreamer\lib\site-packages\gi\module.py", line 267, in get_introspection_module
    module = IntrospectionModule(namespace, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\opt\gstreamer\lib\site-packages\gi\module.py", line 114, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Typelib file for namespace 'GObject', version '2.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\opt\gstreamer\lib\site-packages\gi\importer.py", line 141, in create_module
    raise ImportError(e)
ImportError: Typelib file for namespace 'GObject', version '2.0' not found
>>>

```
