### ISSUE TITLE
Make experimental-ui run on Ubuntu 14.04

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#52]
NB: add libglib2.0-bin to build-deps.  Also install gnome-themes-standard gnome-icon-theme-full gnome-icon-theme-symbolic if you've got an X-less Vagrant instance.

Fatal errors first:
```
(gtimelog:19915): Gtk-ERROR **: failed to add UI: src/gtimelog/experiment.ui: required gtk+ version 3.16, current version is 3.10
Trace/breakpoint trap (core dumped)
```

Fixed by editing the required version in experiment.ui.

Next:

```
Traceback (most recent call last):
  File "./mockup.py", line 157, in do_command_line
    self.do_activate()
  File "./mockup.py", line 235, in do_activate
    window = Window(self)
  File "./mockup.py", line 344, in __init__
    copy_properties(main_window, self)
  File "./mockup.py", line 252, in copy_properties
    if prop.flags & GObject.ParamFlags.READWRITE != GObject.ParamFlags.READWRITE:
AttributeError: type object 'PyGObjectParamFlags' has no attribute 'READWRITE'
```

The docs don't say when READWRITE was introduced.  There's READABLE and WRITABLE.

Next:

```
Traceback (most recent call last):
  File "./mockup.py", line 157, in do_command_line
    self.do_activate()
  File "./mockup.py", line 235, in do_activate
    window = Window(self)
  File "./mockup.py", line 394, in __init__
    self.actions = self.Actions(self)
  File "./mockup.py", line 300, in __init__
    self.detail_level = Gio.PropertyAction.new("detail-level", win, "detail-level")
ValueError: Pointer arguments are restricted to integers, capsules, and None. See: https://bugzilla.gnome.org/show_bug.cgi?id=683599
```

This might be hard to fix; I commented out all PropertyActions temporarily.  Now it runs, but looks terrible (no theme? no icons?  my vagrant is incomplete).

BTW in runs on Python 2, but not 3:

```
Traceback (most recent call last):
  File "./mockup.py", line 157, in do_command_line
    self.do_activate()
  File "./mockup.py", line 235, in do_activate
    window = Window(self)
  File "./mockup.py", line 412, in __init__
    self.load_settings()
  File "./mockup.py", line 457, in load_settings
    self.gsettings.set_string('name', old_settings.name)
TypeError: Must be string, not bytes
```

and on Python 2 some UI elements are out of order -- probably because of

```
(gtimelog:20290): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `GtkHeaderBar' is not writable
```

**Comment by mgedmin** [comment]
Here are all the warnings:
```
Traceback (most recent call last):
  File "./mockup.py", line 172, in do_startup
    self.set_accels_for_action("win.detail-level::chronological", ["<Alt>1"])
AttributeError: 'Application' object has no attribute 'set_accels_for_action'

(gtimelog:21203): Gtk-WARNING **: Unknown property: GtkBox.margin-start

(gtimelog:21203): Gtk-WARNING **: Unknown property: GtkBox.margin-end
./mockup.py:333: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder = Gtk.Builder.new_from_file(UI_FILE)

(gtimelog:21203): Gtk-WARNING **: Unknown property: GtkButtonBox.margin-start

(gtimelog:21203): Gtk-WARNING **: Unknown property: GtkButtonBox.margin-end
./mockup.py:333: Warning: The property GtkToggleButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder = Gtk.Builder.new_from_file(UI_FILE)

(gtimelog:21203): Gtk-WARNING **: Unknown property: GtkTextView.monospace

(gtimelog:21203): Gtk-WARNING **: Unknown property: GtkBox.margin-start

(gtimelog:21203): Gtk-WARNING **: Unknown property: GtkBox.margin-end

(gtimelog:21203): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `GtkHeaderBar' is not writable
./mockup.py:333: Warning: The property GtkMenuButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder = Gtk.Builder.new_from_file(UI_FILE)

(gtimelog:21203): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `GtkHeaderBar' is not writable

(gtimelog:21203): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `GtkHeaderBar' is not writable

(gtimelog:21203): Gtk-WARNING **: /build/gtk+3.0-3sSotQ/gtk+3.0-3.10.8/./gtk/gtkcontainer.c:1166: child property `position' of container class `GtkHeaderBar' is not writable
./mockup.py:836: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  completion = Gtk.EntryCompletion()
./mockup.py:1336: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.append_column(column)
./mockup.py:432: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.gsettings = Gio.Settings.new("org.gtimelog")
```

**Comment by mgedmin** [comment]
And this is the terrible end result:
![ekrano nuotrauka is 2015-09-12 11-00-31](https://cloud.githubusercontent.com/assets/159967/9830595/8968c6ce-593d-11e5-8f40-b26fb0727454.png)

**Comment by mgedmin** [comment]
And here's the diff to get it to that state:
```diff
diff --git a/mockup.py b/mockup.py
index f6f6ac5..2956295 100755
--- a/mockup.py
+++ b/mockup.py
@@ -246,10 +246,11 @@ class Application(Gtk.Application):
 
 def copy_properties(src, dest):
     blacklist = ('events', 'child', 'parent', 'input-hints', 'buffer', 'tabs', 'completion', 'model', 'type')
+    RW = GObject.ParamFlags.READABLE | GObject.ParamFlags.WRITABLE # GObject.ParamFlags.READWRITE missing in GTK+ 3.10
     for prop in src.props:
         if prop.flags & GObject.ParamFlags.DEPRECATED != 0:
             continue
-        if prop.flags & GObject.ParamFlags.READWRITE != GObject.ParamFlags.READWRITE:
+        if prop.flags & RW != RW:
             continue
         if prop.name in blacklist:
             continue
@@ -296,20 +297,20 @@ class Window(Gtk.ApplicationWindow):
     class Actions(object):
 
         def __init__(self, win):
-            self.detail_level = Gio.PropertyAction.new("detail-level", win, "detail-level")
-            win.add_action(self.detail_level)
+##          self.detail_level = Gio.PropertyAction.new("detail-level", win, "detail-level")
+##          win.add_action(self.detail_level)
 
-            self.time_range = Gio.PropertyAction.new("time-range", win, "time-range")
-            win.add_action(self.time_range)
+##          self.time_range = Gio.PropertyAction.new("time-range", win, "time-range")
+##          win.add_action(self.time_range)
 
-            self.show_view_menu = Gio.PropertyAction.new("show-view-menu", win.view_button, "active")
-            win.add_action(self.show_view_menu)
+##          self.show_view_menu = Gio.PropertyAction.new("show-view-menu", win.view_button, "active")
+##          win.add_action(self.show_view_menu)
 
-            self.show_task_pane = Gio.PropertyAction.new("show-task-pane", win.task_pane, "visible")
-            win.add_action(self.show_task_pane)
+##          self.show_task_pane = Gio.PropertyAction.new("show-task-pane", win.task_pane, "visible")
+##          win.add_action(self.show_task_pane)
 
-            self.show_menu = Gio.PropertyAction.new("show-menu", win.menu_button, "active")
-            win.add_action(self.show_menu)
+##          self.show_menu = Gio.PropertyAction.new("show-menu", win.menu_button, "active")
+##          win.add_action(self.show_menu)
 
             for action_name in ['go-back', 'go-forward', 'go-home', 'add-entry', 'report', 'send-report', 'cancel-report']:
                 action = Gio.SimpleAction.new(action_name, None)
diff --git a/src/gtimelog/experiment.ui b/src/gtimelog/experiment.ui
index 4d8c7f9..9fb948f 100644
--- a/src/gtimelog/experiment.ui
+++ b/src/gtimelog/experiment.ui
@@ -1,7 +1,7 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <!-- Generated with glade 3.18.1 -->
 <interface>
-  <requires lib="gtk+" version="3.16"/>
+  <requires lib="gtk+" version="3.10"/>
   <object class="GtkImage" id="image1">
     <property name="visible">True</property>
     <property name="can_focus">False</property>
```

**Comment by mgedmin** [comment]
Checklist:

- [ ] reduce GTK version requirement to 3.10
- [ ] handle missing margin_start/margin_end (use margin_left/margin_right)
- [ ] handle missing GObject.ParamFlags.READWRITE
- [ ] find a replacement for Gio.PropertyAction
- [ ] reorder items in the .ui file so position is not needed
- [ ] handle missing Application.set_accels_for_action()
- [ ] figure out missing symbolic icons 
- [ ] fix deprecation warnings if possible

**Comment by mgedmin** [comment]
http://packages.ubuntu.com/search?searchon=contents&keywords=open-menu-symbolic.svg&mode=exactfilename&suite=trusty&arch=any :(

**Comment by mgedmin** [comment]
(One of the deprecation warnings is #51.)

**Comment by mgedmin** [comment]
Some other things are very unpleasant and probably can't be fixed
- clicking the nav buttons twice in a short time triggers the headerbar double-click action and maximizes the window

**Comment by mgedmin** [comment]
- [ ] the properties dialog doesn't work (there's no "use-header-bar" in GTK+ 3.10)

**Comment by mgedmin** [comment]
There's no header bar for dialogs, and the dialog doesn't even get a close button on the title bar.
- [ ] add a Close button to the preferences dialog's action area.

**Comment by mgedmin** [comment]
Well it ain't pretty, but it works.
