### ISSUE TITLE
PendingDeprecationWarning while running tests on Python 3

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#53]
```
mg@platonas: ~/src/gtimelog [git:experimental-ui $=] $ python3 runtests
....................../usr/lib/python3.4/imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  PendingDeprecationWarning)
...........................................
----------------------------------------------------------------------
Ran 65 tests in 0.944s

OK
```

To get more detail:
```
mg@platonas: ~/src/gtimelog [git:experimental-ui $=] $ PYTHONWARNINGS=error python3 runtests
......................EEEEEEEEEEEEEEFFFFFFFFFF..FFFFFF..F...FF...
======================================================================
ERROR: test_parse_correction_handles_virtual_midnight_todays_time (gtimelog.tests.TestTimeLog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/.local/lib/python3.4/site-packages/freezegun/api.py", line 344, in wrapper
    with self:
  File "/home/mg/.local/lib/python3.4/site-packages/freezegun/api.py", line 257, in __enter__
    self.start()
  File "/home/mg/.local/lib/python3.4/site-packages/freezegun/api.py", line 292, in start
    attribute_value = getattr(module, module_attribute)
  File "/home/mg/.local/lib/python3.4/site-packages/six.py", line 90, in __get__
    result = self._resolve()
  File "/home/mg/.local/lib/python3.4/site-packages/six.py", line 158, in _resolve
    module = _import_module(self.mod)
  File "/home/mg/.local/lib/python3.4/site-packages/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/lib/python3.4/imp.py", line 32, in <module>
    PendingDeprecationWarning)
PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

So freezegun somehow causes six to import imp.

**Comment by mgedmin** [comment]
I think this is the cause: https://github.com/spulec/freezegun/issues/101

**Comment by mgedmin** [comment]
A newer version of freezegun [contains a fix for this](https://github.com/spulec/freezegun/blob/d329d66f11e2cec2fa91b6469e253f0df37c0065/freezegun/api.py#L461).
