### ISSUE TITLE
`gtimelog` would not start with a traceback related to `search_entry`

### ISSUE THREAD

**Issue by laureenas** [gtimelog/gtimelog#90]
Steps to reproduce on my machine:
 
```
$:~/src/gtimelog$ git pull
Already up-to-date.
$:~/src/gtimelog$ git remote -v
origin	git@github.com:gtimelog/gtimelog.git (fetch)
origin	git@github.com:gtimelog/gtimelog.git (push)
$:~/src/gtimelog$ ./gtimelog 
Traceback (most recent call last):
  File "./src/gtimelog/main.py", line 218, in do_command_line
    self.do_activate()
  File "./src/gtimelog/main.py", line 348, in do_activate
    window = Window(self)
  File "./src/gtimelog/main.py", line 595, in __init__
    self.search_entry.connect('search-changed', self.on_search_changed)
AttributeError: 'NoneType' object has no attribute 'connect'
```

**Comment by mgedmin** [comment]
Thank you for the bug report!

Can you run `make` and see if the error goes away?  I've a theory.

**Comment by laureenas** [comment]
Running `make` did fix the problem.  Solved! 

Thank you!

**Comment by mgedmin** [comment]
I wonder if I can make gtimelog detect when the generated .ui files are out of date.  Compare mtimes perhaps?  Or do the preprocessing steps in memory and pass the string to Gtk.Builder()?
